version: "3"

services:
  apisix:
    image: apache/apisix:2.15.0-alpine
    volumes:
      - ./apisix/config.yml:/usr/local/apisix/conf/config.yaml:ro
      - ./apisix/apisix.yml:/usr/local/apisix/conf/apisix.yaml:ro
      - wasm-plugin:/opt/apisix/wasm:ro
    ports:
      - "9080:9080"
  plugin:
    build: ./sample
    volumes:
      - wasm-plugin:/var/wasm

volumes:
  wasm-plugin: ~